name: marker_motion
description: A flutter package that smoothly animates Google Maps markers between two positions
version: 0.1.4
repository: https://github.com/chaosinfernohq/marker_motion

environment:
  sdk: ^3.11.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
